[DOTBOT] Split installation to unix and windows configs

diff --git a/install b/install
--- a/install
+++ b/install
@@ -2,9 +2,18 @@
 
 set -e
 
-CONFIG="install.conf.yaml"
-DOTBOT_DIR="dotbot"
+# Fail fast on Git Bash / MSYS / Cygwin - use install.ps1 instead
+case "$(uname -s)" in
+    MINGW*|MSYS*|CYGWIN*)
+        echo "Error: This installer is not supported on Git Bash/MSYS/Cygwin."
+        echo "Please use PowerShell and run: .\\install.ps1"
+        exit 1
+        ;;
+esac
 
+COMMON_CONFIG="install.conf.yaml"
+UNIX_CONFIG="install.unix.conf.yaml"
+DOTBOT_DIR="dotbot"
 DOTBOT_BIN="bin/dotbot"
 BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
@@ -12,4 +21,7 @@ cd "${BASEDIR}"
 git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
 git submodule update --init --recursive "${DOTBOT_DIR}"
 
-"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
+"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" \
+    -c "${COMMON_CONFIG}" \
+    -c "${UNIX_CONFIG}" \
+    "${@}"
